### PR TITLE
Small fix in link

### PR DESCRIPTION
**Pull request by Sukriti-sood**
It's not good practice to put links as its, 😅

### CODE REVIEW

**Review by Abhijay007 — COMMENTED** [review]
@Sukriti-sood  DCO left :)

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood DCO left :)

Yes, I did it from github so there is no option to signed the commit, I have to makr local copy. I hope Github will launch this feature soon.

**Review by joewxboy — CHANGES_REQUESTED** [review]
I think someone confused directions to hyperlink some text with text that was actually inserted.

-----

As a developer you can use Github issues and discussions on the respective repositories to report bugs, request features, and discuss changes. We recommend using issues to connect with maintainers, contributors and other community members. As a user, you can use the [open horizon](https://www.lfedge.org/projects/openhorizon/) website to connect with us and let's link maintainers, contributors and other community members to the community page on the wiki that explains what those roles are [here](https://wiki.lfedge.org/display/OH/Community+Membership).

-----

should probably be more like this:

As a developer you should use Github issues and discussions on the respective repositories to report bugs, request features, and discuss changes. Use issues to connect with [maintainers, contributors and other community members](https://wiki.lfedge.org/display/OH/Community+Membership). New users may want to visit and bookmark the [Open Horizon project web site](https://www.lfedge.org/projects/openhorizon/) to connect with the community and to learn more about the software solution.

**Comment by joewxboy** [comment]
A few best practices:
* Always capitalize proper nouns such as project names: Open Horizon
* The repository name is not a proper noun: open-horizon
* Hyperlink text should be descriptive of what you're linking to, and as such, should never be text like "click here".
* Try not to use personal pronouns in your text like I, us, and we (even though it sounds more friendly).

**Comment by Sukriti-sood** [comment]
> A few best practices:
> 
> * Always capitalize proper nouns such as project names: Open Horizon
> * The repository name is not a proper noun: open-horizon
> * Hyperlink text should be descriptive of what you're linking to, and as such, should never be text like "click here".
> * Try not to use personal pronouns in your text like I, us, and we (even though it sounds more friendly).

According to me, this is great stuff. We should put this in one place. We can have an Open Horizon style guide (markdown) or we can put all this in [open-horizon.github.io](https://github.com/open-horizon/open-horizon.github.io) wiki as mentioned here[https://github.com/open-horizon/open-horizon.github.io/issues/25]

**Comment by joewxboy** [comment]
> According to me, these are great practices. We should put this in one place. We can have an Open Horizon style guide (markdown) or we can put all this in [open-horizon.github.io](https://github.com/open-horizon/open-horizon.github.io) wiki as mentioned here[https://github.com/[open-horizon/open-horizon.github.io/issues/25](https://github.com/open-horizon/open-horizon.github.io/issues/25)]. And we should put them in [open-horizon.github.io](https://github.com/open-horizon/open-horizon.github.io) readme for every contributor to follow these guidlines.

Yup.  I wanted to write it down here before I forgot those points.  My earlier comment/requested changes reminded me.

https://github.com/open-horizon/.github/pull/8#pullrequestreview-888077240

**Review by joewxboy — APPROVED** [review]

**Comment by joewxboy** [comment]
@Sukriti-sood I like your "check this view" link best.

**Pull request merged**
